name: gaming

services:
  postgres:
    image: postgres
    container_name: gaming-postgres
    environment:
      POSTGRES_DB: gaming
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5432:5432'
    volumes:
      - gaming_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  gaming_postgres_data:

